Added all the necessary scripts

diff --git a/images/contestant/files/scripts/self_test b/images/contestant/files/scripts/self_test
--- a/images/contestant/files/scripts/self_test
+++ b/images/contestant/files/scripts/self_test
@@ -76,11 +76,11 @@ HOSTNAME="$(hostname)"
 echo $HOSTNAME
 print_check "Timezone"
 TIMEZONE="$(timedatectl show -p Timezone 2>/dev/null)"
-# if [ $TIMEZONE = "{{ icpc_timezone }}" ]; then
-#   TIMEZONE="${GREEN}${TIMEZONE}${RESET}"
-# else
-#   TIMEZONE="${RED}${TIMEZONE}${RESET}"
-# fi
+if [ $TIMEZONE = "Timezone=Europe/Amsterdam" ]; then
+  TIMEZONE="${GREEN}${TIMEZONE}${RESET}"
+else
+  TIMEZONE="${RED}${TIMEZONE}${RESET}"
+fi
 echo $TIMEZONE
 print_check "Team Name"
 TEAMNAME="$(cat /icpc/TEAM 2>/dev/null)"
@@ -92,22 +92,22 @@ ROOM="$(cat /icpc/ROOM 2>/dev/null)"
 NOROOM="${RED}Not Set${RESET}"
 ROOM="${ROOM:-$NOROOM}"
 echo $ROOM
-# print_check "DOMjudge Autologin Configured"
-# cat /etc/squid/autologin.conf 2>/dev/null | grep "X-DOMjudge" > /dev/null
-# if [ $? -eq 0 ]; then
-#   DJTEAM=$(cat /etc/squid/autologin.conf | awk '/X-DOMjudge-Login/{print $3}' | tr -d '"')
-#   DJPASS=$(cat /etc/squid/autologin.conf | awk '/X-DOMjudge-Pass/{print $3}' | tr -d '"' | base64 --decode)
-#   HTTPCODE=$(curl -s -o /dev/null -w "%{http_code}" -X 'GET' -u "${DJTEAM}:${DJPASS}" 'https://{{ domjudge_url }}/api/v4/user' -H 'accept: application/json' -L)
-#   if [ "$HTTPCODE" == "200" ]; then
-#     echo "${GREEN}Yes${RESET}"
-#   else
-#     echo "${RED}ERROR ${HTTPCODE}${RESET}"
-#   fi
-#   print_check "    Team Login"
-#   echo $DJTEAM
-# else
-#   echo "${ORANGE}No${RESET}"
-# fi
+print_check "DOMjudge Autologin Configured"
+cat /etc/squid/autologin.conf 2>/dev/null | grep "X-DOMjudge" > /dev/null
+if [ $? -eq 0 ]; then
+  DJTEAM=$(cat /etc/squid/autologin.conf | awk '/X-DOMjudge-Login/{print $3}' | tr -d '"')
+  DJPASS=$(cat /etc/squid/autologin.conf | awk '/X-DOMjudge-Pass/{print $3}' | tr -d '"' | base64 --decode)
+  HTTPCODE=$(curl -s -o /dev/null -w "%{http_code}" -X 'GET' -u "${DJTEAM}:${DJPASS}" 'https://dj.chipcie.ch.tudelft.nl/api/v4/user' -H 'accept: application/json' -L)
+  if [ "$HTTPCODE" == "200" ]; then
+    echo "${GREEN}Yes${RESET}"
+  else
+    echo "${RED}ERROR ${HTTPCODE}${RESET}"
+  fi
+  print_check "    Team Login"
+  echo $DJTEAM
+else
+  echo "${ORANGE}No${RESET}"
+fi
 
 echo
 echo "${BLUE}Printing Configuration${RESET}"
@@ -136,9 +136,9 @@ print_check "Testing access to google is blocked with a proxy error"
 wget -e use_proxy=yes --timeout=5 -t 1 -e http_proxy=127.0.0.1:3128 -O- http://google.com 2>/dev/null | grep "<h1>Access Denied</h1>" > /dev/null
 check_return $?
 
-# print_check "Testing access to DOMjudge is successful with proxy"
-# wget -e use_proxy=yes --timeout=5 -t 1 -e http_proxy=127.0.0.1:3128 -O- --no-check-certificate {{ domjudge_url }} 2>/dev/null | grep "DOMjudge" > /dev/null
-# check_return $?
+print_check "Testing access to DOMjudge is successful with proxy"
+wget -e use_proxy=yes --timeout=5 -t 1 -e http_proxy=127.0.0.1:3128 -O- --no-check-certificate dj.chipcie.ch.tudelft.nl 2>/dev/null | grep "DOMjudge" > /dev/null
+check_return $?
 
 print_check "Testing direct internet access is disabled"
 su - contestant -c 'wget -T 5 -t 1 -e use_proxy=no -O- http://google.com >/dev/null 2>&1' 2>/dev/null
@@ -186,3 +186,4 @@ echo "${BLUE}Image Details${RESET}"
 VERSIONINFO=$(cat /icpc/version 2>/dev/null)
 VERSIONDEFAULT="${RED}No version info found!${DEFAULT}"
 echo -e "${VERSIONINFO:-$VERSIONDEFAULT}"
+
